version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-building..."
  build:
    commands:
      - echo "Building..."

  post_build:
    commands:
      - echo "Creating package..."
